version: "3"

services:
  master:
    build:
      context: "./master"
    depends_on:
      - aux1
      - aux2
      - aux3
    environment:
      - ROLE=primary
      - STANDBY_SERVER=master-standby:8000
      - AUX_SERVERS=aux1:3001,aux2:3002,aux3:3003
      - PORT=8000
    volumes:
      - ./master:/app
      - ./data:/data
    networks:
      - cache-network

  master-standby:
    build:
      context: "./master"
    depends_on:
      - master
    environment:
      - ROLE=standby
      - PRIMARY_MASTER=master:8000
      - AUX_SERVERS=aux1:3001,aux2:3002,aux3:3003
      - PORT=8000
    volumes:
      - ./master:/app
      - ./data:/data
    networks:
      - cache-network

  nginx:
    image: "nginx"
    depends_on:
      - master
      - master-standby
    ports:
      - 8080:3000
    volumes:
      - ./nginx/conf.d:/etc/nginx/
    networks:
      - cache-network

  aux1:
    build:
      context: "./auxiliary"
    restart: unless-stopped
    environment:
      - PORT=3001
      - MASTER_SERVER=nginx:3000
      - ID=aux1
      - LRU_CAPACITY=128
    ports:
      - 9001:3001
    volumes:
      - ./auxiliary:/app
      - ./data:/data
    networks:
      - cache-network

  aux2:
    build:
      context: "./auxiliary"
    restart: unless-stopped
    environment:
      - PORT=3002
      - MASTER_SERVER=nginx:3000
      - ID=aux2
      - LRU_CAPACITY=128
    ports:
      - 9002:3002
    volumes:
      - ./auxiliary:/app
      - ./data:/data
    networks:
      - cache-network

  aux3:
    build:
      context: "./auxiliary"
    restart: unless-stopped
    environment:
      - PORT=3003
      - MASTER_SERVER=nginx:3000
      - ID=aux3
      - LRU_CAPACITY=128
    ports:
      - 9003:3003
    volumes:
      - ./auxiliary:/app
      - ./data:/data
    networks:
      - cache-network

  aux4:
    build:
      context: "./auxiliary"
    restart: unless-stopped
    environment:
      - PORT=3004
      - MASTER_SERVER=nginx:3000
      - ID=aux4
      - LRU_CAPACITY=128
    ports:
      - 9004:3004
    volumes:
      - ./auxiliary:/app
      - ./data:/data
    networks:
      - cache-network

  # Metrics
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cache-network

  grafana:
    image: grafana/grafana
    ports:
      - 4000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - cache-network

networks:
  cache-network:
