worker_processes auto;

events {
    worker_connections 2048;
}

http {
    keepalive_timeout 75s;
    keepalive_requests 1000;

    proxy_http_version 1.1;
    proxy_set_header Connection "";

    upstream masters {
        server master:8000 max_fails=3 fail_timeout=15s;
        server master-standby:8000 backup;
    }

    server {
        listen 3000;
        location / {
            proxy_pass http://masters/;
            proxy_connect_timeout 2s;
            proxy_read_timeout 15s;
            proxy_next_upstream error timeout;
        }
    }
}
